name: logger_micro_service

services:
  logger_micro_service:
    image: registry.cn-hangzhou.aliyuncs.com/hardensg/logger:latest
    expose:
      - "3001" # 如果是负载均衡就不能启动固定端口映射
    environment:
      - LANG=C.UTF-8 # 打印的内容编码为UTF8
    volumes: 
      - /opt/cert:/opt/cert # 同步本地的/opt/cert目录到docker数据卷
    networks:
      - same_network

volumes:
  mongo-data:

networks:
  same_network:
    external: true
    name: dynamic_config_same_network